# Generated by Django 4.2.4 on 2023-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bl_number", models.CharField(max_length=20)),
                ("plate_number", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Truck Informantion",
                "verbose_name_plural": "Truck Information",
            },
        ),
    ]
