# Generated by Django 4.2.4 on 2023-08-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trucks", "0001_initial"),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverInfo",
            fields=[
                (
                    "name_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.name",
                    ),
                ),
                ("profile_pic", models.ImageField(upload_to="users/")),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True)),
                (
                    "assigned_truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trucks.truckinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Information",
                "verbose_name_plural": "Driver Informations",
                "ordering": ["first_name"],
            },
            bases=("base.name",),
        ),
    ]
