# Generated by Django 4.2.4 on 2023-08-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trucks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Enter First Name", max_length=30),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter SurName e.g Father's Name", max_length=30
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter Middle Name",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("DL", "Driver's License"),
                            ("IP", "Int'l Passport"),
                            ("NI", "NIN"),
                        ],
                        max_length=3,
                    ),
                ),
                ("id_number", models.CharField(max_length=12)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Enter representative's Phone Number, 11 digits",
                        max_length=11,
                    ),
                ),
                ("profile_pic", models.ImageField(upload_to="users/")),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True)),
                (
                    "assigned_truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trucks.truckinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Information",
                "verbose_name_plural": "Driver Informations",
                "ordering": ["first_name"],
            },
        ),
    ]
