# Generated by Django 4.2.4 on 2023-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Enter Name of client", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter SurName of client", max_length=50
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter Middle Name of client",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("DL", "Driver's License"),
                            ("IP", "Int'l Passport"),
                            ("NI", "NIN"),
                        ],
                        max_length=3,
                    ),
                ),
                ("id_number", models.CharField(max_length=11)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Enter representative's Phone Number, 11 digits",
                        max_length=11,
                    ),
                ),
            ],
        ),
    ]
