# Generated by Django 4.2.4 on 2023-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyTrips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("TP", "TRIP")], default="TP", max_length=2
                    ),
                ),
                (
                    "initials",
                    models.CharField(
                        help_text="Enter Company Name Initials", max_length=5
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("proposal", models.FileField(upload_to="proposals/")),
            ],
        ),
        migrations.CreateModel(
            name="IndividualTrips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("TP", "TRIP")], default="TP", max_length=2
                    ),
                ),
                (
                    "initials",
                    models.CharField(help_text="Enter Fullname Initials", max_length=5),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("proposal", models.FileField(upload_to="proposals/")),
            ],
        ),
    ]
