# Generated by Django 4.2.4 on 2023-08-31 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companytrips",
            options={
                "verbose_name": "Individual Trip",
                "verbose_name_plural": "Individual Trips",
            },
        ),
        migrations.AlterModelOptions(
            name="individualtrips",
            options={
                "verbose_name": "Individual Trip",
                "verbose_name_plural": "Individual Trips",
            },
        ),
    ]
