# Generated by Django 4.2.4 on 2023-08-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Enter First Name", max_length=30),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter SurName e.g Father's Name", max_length=30
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter Middle Name",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("DL", "Driver's License"),
                            ("IP", "Int'l Passport"),
                            ("NI", "NIN"),
                        ],
                        max_length=3,
                    ),
                ),
                ("id_number", models.CharField(max_length=12)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Enter representative's Phone Number, 11 digits",
                        max_length=11,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("I", "Individual")], default="I", max_length=15
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=4, max_digits=10)),
                ("con_type", models.CharField(max_length=100)),
                ("take_off_location", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True)),
                (
                    "driver_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drivers.driverinfo",
                    ),
                ),
                (
                    "trip_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trips.individualtrips",
                    ),
                ),
            ],
            options={
                "verbose_name": "IndividualOrder",
                "verbose_name_plural": "IndividualOrders",
            },
        ),
        migrations.CreateModel(
            name="OrderCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Enter First Name", max_length=30),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter SurName e.g Father's Name", max_length=30
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter Middle Name",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("DL", "Driver's License"),
                            ("IP", "Int'l Passport"),
                            ("NI", "NIN"),
                        ],
                        max_length=3,
                    ),
                ),
                ("id_number", models.CharField(max_length=12)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Enter representative's Phone Number, 11 digits",
                        max_length=11,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("C", "Company")], default="I", max_length=15
                    ),
                ),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("cac_no", models.CharField(blank=True, max_length=10, null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=4)),
                ("con_type", models.CharField(max_length=100)),
                ("take_off_location", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True)),
                (
                    "driver_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drivers.driverinfo",
                    ),
                ),
                (
                    "trip_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trips.companytrips",
                    ),
                ),
            ],
            options={
                "verbose_name": "CompanyOrder",
                "verbose_name_plural": "CompanyOrders",
                "ordering": ["company_name"],
            },
        ),
    ]
