# Generated by Django 4.2.4 on 2023-08-22 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("base", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderIndividual",
            fields=[
                (
                    "name_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.name",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("I", "Individual")], default="I", max_length=15
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=4, max_digits=10)),
                ("con_type", models.CharField(max_length=100)),
                ("take_off_location", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True)),
                (
                    "driver_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drivers.driverinfo",
                    ),
                ),
                (
                    "trip_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trips.individualtrips",
                    ),
                ),
            ],
            options={
                "verbose_name": "IndividualOrder",
                "verbose_name_plural": "IndividualOrders",
            },
            bases=("base.name",),
        ),
        migrations.CreateModel(
            name="OrderCompany",
            fields=[
                (
                    "name_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.name",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("C", "Company")], default="I", max_length=15
                    ),
                ),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("cac_no", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MaxValueValidator(45.0)],
                    ),
                ),
                ("con_type", models.CharField(max_length=100)),
                ("take_off_location", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True)),
                (
                    "driver_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drivers.driverinfo",
                    ),
                ),
                (
                    "trip_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trips.companytrips",
                    ),
                ),
            ],
            options={
                "verbose_name": "CompanyOrder",
                "verbose_name_plural": "CompanyOrders",
                "ordering": ["company_name"],
            },
            bases=("base.name",),
        ),
    ]
