# Generated by Django 4.2.4 on 2023-08-31 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordercompany",
            options={
                "ordering": ["company_name"],
                "verbose_name": "Company Order",
                "verbose_name_plural": "Company Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderindividual",
            options={
                "verbose_name": "Individual Order",
                "verbose_name_plural": "Individual Orders",
            },
        ),
    ]
