# Generated by Django 4.2.4 on 2023-09-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_ordercompany_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercompany",
            name="cac_no",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
