# Generated by Django 4.2.4 on 2023-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_ordercompany_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercompany",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
