# Generated by Django 4.2.4 on 2023-09-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_ordercompany_cac_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercompany",
            name="middle_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Enter Middle Name",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderindividual",
            name="middle_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Enter Middle Name",
                max_length=30,
                null=True,
            ),
        ),
    ]
